#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Deploy the hue-grpc gateway to this NixOS host and run the issue #16 smoke
# test against the real Philips Hue bridge that runs the house.
#
# Run it ON the NixOS box, FROM a checkout of this repo:
#
#     bash scripts/deploy-and-smoke-test.sh
#
# It needs sudo (nixos-rebuild, journalctl), LAN access to the bridge, and a
# phone with the Hue app for the two stages a person has to drive by hand.
# Stop with Ctrl-C at any point and re-run: pairing, the credentials file and
# the captured values are all picked up again rather than redone.
#
#     bash scripts/deploy-and-smoke-test.sh --skip-deploy
#
# skips everything that needs a booted NixOS with systemd — the credentials
# file, the module config, `nixos-rebuild switch`, the journal scan — and
# instead runs the gateway itself from `nix build`. That covers pair, list,
# read, change/restore, the event stream and its gap/resync on any Linux box
# (a nix container, say) that can reach the bridge. No sudo.

DEPLOY=1
for arg in "$@"; do
  case "$arg" in
    --skip-deploy) DEPLOY=0 ;;
    -h | --help)
      echo "usage: bash scripts/deploy-and-smoke-test.sh [--skip-deploy]"
      exit 0
      ;;
    *)
      echo "unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

TOTAL_STAGES=$([[ $DEPLOY == 1 ]] && echo 10 || echo 8)

# The record the wizard leaves behind, per issue #16's "Record" section.
ENV_FILE="${REPORT_FILE:-issue-16-smoke-report.env}"

FLAKE="${FLAKE:-.}"                      # this repo — for `nix run . -- pair`
GW="127.0.0.1:50051"                     # the module's default loopback listener
UNIT="hue-grpc.service"
CRED_FILE="${CRED_FILE:-/etc/hue-grpc/credentials}"
BRIDGE_ADDRESS_DEFAULT="192.168.86.223"
BRIDGE_ID_DEFAULT="ECB5FAFFFE334703"
REG="${XDG_STATE_HOME:-$HOME/.local/state}/hue-grpc/registry.json"
SUB="${TMPDIR:-/tmp}/hue-events.ndjson"
JOURNAL="${TMPDIR:-/tmp}/hue-journal.txt"
GWLOG="${TMPDIR:-/tmp}/hue-gateway.log"     # --skip-deploy: the gateway's own stderr
GWRESULT="${TMPDIR:-/tmp}/hue-wizard-result"
SUBPID=""
GWPID=""
KEY_TMP=""

# grpcurl, jq and curl are not in a base NixOS PATH; re-exec once inside a shell
# that has them (everything else — nix, systemctl, nixos-rebuild — is already
# on PATH).
if { ! command -v grpcurl >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; } \
   && [[ -z "${_HUE_WIZARD_REEXEC:-}" ]] && command -v nix >/dev/null 2>&1; then
  export _HUE_WIZARD_REEXEC=1
  echo "  fetching grpcurl + jq + curl via nix shell ..."
  exec nix shell nixpkgs#grpcurl nixpkgs#jq nixpkgs#curl --command bash "$0" "$@"
fi

# shred_file PATH — wipe a file that held secret material, best effort.
shred_file() {
  [[ -f "$1" ]] || return 0
  if command -v shred >/dev/null 2>&1; then shred -u "$1" 2>/dev/null && return 0; fi
  rm -f "$1"
}

cleanup() {
  [[ -n "$SUBPID" ]] && kill "$SUBPID" 2>/dev/null || true
  [[ -n "$GWPID" ]] && kill "$GWPID" 2>/dev/null || true
  [[ -n "$KEY_TMP" ]] && shred_file "$KEY_TMP"
}
trap cleanup EXIT

# count_in FILE PATTERN — count of matching lines, always a number, 0 when the
# file or the match is absent (grep exits non-zero on no match, which pipefail
# would otherwise turn into a wizard-ending error).
count_in() {
  local n
  n="$(grep -Fc -- "$2" "$1" 2>/dev/null || true)"
  printf '%s' "${n:-0}"
}

banner "hue-grpc · $([[ $DEPLOY == 1 ]] && echo 'deploy to NixOS and ')smoke-test the real bridge"

# ── preflight ───────────────────────────────────────────────────────────
stage "Preflight and bridge identity"
if [[ $DEPLOY == 1 ]]; then
  say "Run this on the NixOS host that will run the gateway, from this repo."
  tools="nix nixos-rebuild systemctl journalctl systemd-analyze grpcurl jq curl"
else
  say "--skip-deploy: pair, smoke-test and run the gateway here, no systemd."
  tools="nix grpcurl jq curl"
fi
missing=""
for t in $tools; do
  command -v "$t" >/dev/null 2>&1 || { warn "missing on PATH: $t"; missing=1; }
done
[[ -z "$missing" ]] || { warn "install the above and re-run"; exit 1; }

note "defaults in [brackets] — press Enter to accept"
ask HUE_BRIDGE_ADDRESS "Bridge address [$BRIDGE_ADDRESS_DEFAULT]:"
HUE_BRIDGE_ADDRESS="${HUE_BRIDGE_ADDRESS:-$BRIDGE_ADDRESS_DEFAULT}"
ask HUE_BRIDGE_ID "Bridge ID [$BRIDGE_ID_DEFAULT]:"
HUE_BRIDGE_ID="${HUE_BRIDGE_ID:-$BRIDGE_ID_DEFAULT}"

step "GET https://$HUE_BRIDGE_ADDRESS/api/config  (needs no Application Key)"
cfg="$(curl -sk --max-time 10 "https://$HUE_BRIDGE_ADDRESS/api/config")" \
  || { warn "cannot reach the bridge at $HUE_BRIDGE_ADDRESS"; exit 1; }
b_name="$(jq -r '.name        // "?"' <<<"$cfg")"
b_model="$(jq -r '.modelid    // "?"' <<<"$cfg")"
b_sw="$(jq -r '.swversion     // "?"' <<<"$cfg")"
b_api="$(jq -r '.apiversion   // "?"' <<<"$cfg")"
b_id="$(jq -r '.bridgeid      // "?"' <<<"$cfg")"
say "name       $b_name"
say "model      $b_model"
say "firmware   $b_sw   (CLIP api $b_api)"
say "bridge id  $b_id"
if [[ "${b_id,,}" != "${HUE_BRIDGE_ID,,}" ]]; then
  warn "the bridge reports id $b_id, not the $HUE_BRIDGE_ID you gave"
  confirm "Continue against this bridge anyway?" || exit 1
fi
STARTED_AT="$(date -Is)"
write_env HUE_BRIDGE_ADDRESS "$HUE_BRIDGE_ADDRESS"
write_env HUE_BRIDGE_ID      "$HUE_BRIDGE_ID"
write_env BRIDGE_NAME        "$b_name"
write_env BRIDGE_MODEL       "$b_model"
write_env BRIDGE_FIRMWARE    "$b_sw"
write_env BRIDGE_APIVERSION  "$b_api"
write_env SMOKE_STARTED_AT   "$STARTED_AT"

# ── pair ────────────────────────────────────────────────────────────────
stage "Pair with the bridge — physical button press"
if [[ -f "$REG" ]] && jq -e '.bridge.application_key' "$REG" >/dev/null 2>&1; then
  say "A registry already exists at:"
  note "  $REG"
  say "Reusing the Application Key it holds. Pairing again would mint a second"
  say "key and strand this one in the bridge's app list, removable only from"
  say "the Hue app."
else
  warn "This mints a REAL Application Key and only works within ~30 seconds of"
  warn "pressing the bridge's link button."
  # Build the gateway before the button press, not inside the retry loop: a
  # build failure is not a pairing failure, and 30 seconds is not the time to
  # discover the binary won't compile.
  say "building the gateway (cached after the first run) ..."
  if ! nix build "$FLAKE#hue-grpc" -o "$GWRESULT" --print-build-logs; then
    warn "the gateway did not build — fix that above, then re-run."
    warn "a bare 'g++ ... exit code 1' with no diagnostic is usually the build"
    warn "host running out of memory on grpcio-tools; give it more RAM + swap."
    exit 1
  fi
  hue_cli="$GWRESULT/bin/hue-grpc-server"
  pause "Walk to the bridge, press the round link button on top, come back, Enter."
  paired=""
  for attempt in 1 2 3; do
    say "pairing (attempt $attempt/3) ..."
    if "$hue_cli" pair \
      --bridge-address "$HUE_BRIDGE_ADDRESS" --bridge-id "$HUE_BRIDGE_ID"; then
      paired=1
      break
    fi
    warn "that did not take — press the link button again, within 30s of Enter"
    pause "Enter to retry"
  done
  [[ -n "$paired" ]] || { warn "pairing did not succeed"; exit 1; }
fi
APP_KEY="$(jq -r '.bridge.application_key' "$REG")"
CLIENT_KEY="$(jq -r '.bridge.client_key // empty' "$REG")"
[[ -n "$APP_KEY" && "$APP_KEY" != null ]] \
  || { warn "no application key in $REG"; exit 1; }
say "Application Key present (${#APP_KEY} chars — not shown, not recorded)."

if [[ $DEPLOY == 1 ]]; then
  # ── 3 ──────────────────────────────────────────────────────────────────
  stage "Install the Credentials File"
  say "systemd LoadCredential hands this to the service. Root-owned, mode 0600,"
  say "outside the Nix store, never an ExecStart argument."
  note "  $CRED_FILE"
  KEY_TMP="$(mktemp)"
  printf 'application-key=%s\n' "$APP_KEY" > "$KEY_TMP"
  [[ -n "$CLIENT_KEY" ]] && printf 'client-key=%s\n' "$CLIENT_KEY" >> "$KEY_TMP"
  sudo install -D -m 600 -o root -g root "$KEY_TMP" "$CRED_FILE"
  shred_file "$KEY_TMP"
  KEY_TMP=""
  if sudo test -f "$CRED_FILE"; then say "wrote $CRED_FILE"; else warn "write failed"; exit 1; fi
  write_env CREDENTIALS_FILE "$CRED_FILE"

  # ── 4 ──────────────────────────────────────────────────────────────────
  stage "Declare services.hue-grpc in your NixOS configuration"
  say "1. Add the flake input (flake.nix):"
  note '     hue-grpc.url = "github:malamoney/hue";'
  note "     # or a local checkout:  hue-grpc.url = \"git+file://$PWD\";"
  say ""
  say "2. Import the module and configure it (configuration.nix):"
  cat <<EOF

    imports = [ hue-grpc.nixosModules.default ];

    services.hue-grpc = {
      enable = true;
      bridge = {
        address = "$HUE_BRIDGE_ADDRESS";
        id      = "$HUE_BRIDGE_ID";
        credentialsFile = "$CRED_FILE";
      };
    };
EOF
  say ""
  say "Loopback listener on $GW, no firewall change, no TLS — the configuration"
  say "that needs no further decisions. (LAN clients: see the module's grpc.tls"
  say "and grpc.tokenFile options.)"
  confirm "Added that to your configuration and saved it?" \
    || { warn "add it, then re-run — earlier stages will be skipped"; exit 1; }
  ask FLAKE_TARGET "System flake target for nixos-rebuild (e.g. /etc/nixos#$(hostname -s)):"
  [[ -n "$FLAKE_TARGET" ]] || { warn "need a flake target"; exit 1; }
  write_env FLAKE_TARGET "$FLAKE_TARGET"

  # ── 5 ──────────────────────────────────────────────────────────────────
  stage "Deploy"
  say "sudo nixos-rebuild switch --flake $FLAKE_TARGET"
  say "Heavy dependencies come prebuilt from cache.nixos.org; only the small"
  say "pure-Python derivation builds here."
  confirm "Run nixos-rebuild switch now?" || exit 1
  sudo nixos-rebuild switch --flake "$FLAKE_TARGET"
  sleep 2
  if systemctl is-active --quiet "$UNIT"; then
    say "$UNIT is active"
  else
    warn "$UNIT is not active"
    systemctl --no-pager --full status "$UNIT" || true
    exit 1
  fi
  # Type=exec marks the unit active the moment the process is exec'd, before
  # the asyncio server has bound the port. Wait for the listener itself.
  say "waiting for the gRPC listener on $GW ..."
  ready=""
  for _ in $(seq 1 60); do
    if grpcurl -plaintext -d '{}' "$GW" grpc.health.v1.Health/Check >/dev/null 2>&1; then
      ready=1; break
    fi
    sleep 1
  done
  if [[ -z "$ready" ]]; then
    warn "no gRPC listener on $GW after 60s"
    sudo journalctl -u "$UNIT" --no-pager -n 40 || true
    exit 1
  fi
  say "listener up"
  say ""
  say "systemd hardening (issue #15's set, checked live):"
  sec="$(systemd-analyze security "$UNIT" 2>/dev/null | grep -i 'exposure level' || true)"
  say "  ${sec:-(systemd-analyze security produced no summary line)}"
  write_env SYSTEMD_SECURITY "${sec:-unknown}"
else
  # ── 5' ─────────────────────────────────────────────────────────────────
  stage "Start the gateway"
  say "No systemd here — the wizard runs the gateway itself. It reads the"
  say "registry entry pairing just wrote and serves on $GW."
  if [[ ! -x "$GWRESULT/bin/hue-grpc-server" ]]; then
    say "building (heavy deps come from the binary cache) ..."
    if ! nix build "$FLAKE#hue-grpc" -o "$GWRESULT" --print-build-logs; then
      warn "the gateway did not build — see above."
      exit 1
    fi
  fi
  : > "$GWLOG"
  "$GWRESULT/bin/hue-grpc-server" > "$GWLOG" 2>&1 &
  GWPID=$!
  say "waiting for the gRPC listener on $GW ..."
  ready=""
  for _ in $(seq 1 30); do
    if grpcurl -plaintext -d '{}' "$GW" grpc.health.v1.Health/Check >/dev/null 2>&1; then
      ready=1; break
    fi
    if ! kill -0 "$GWPID" 2>/dev/null; then
      warn "the gateway exited during startup:"; sed 's/^/    /' "$GWLOG"; exit 1
    fi
    sleep 1
  done
  [[ -n "$ready" ]] || { warn "no listener on $GW after 30s"; tail -n 40 "$GWLOG" | sed 's/^/    /'; exit 1; }
  say "listener up (pid $GWPID, log $GWLOG)"
fi

# ── smoke: list + read ──────────────────────────────────────────────────
stage "Smoke: list the lights, read the one to test"
grpcurl -plaintext -d '{}' "$GW" hue.v1.LightingService/ListLights \
  > ./issue-16-lights-inventory.json
n_lights="$(jq '(.lights // []) | length' ./issue-16-lights-inventory.json)"
say "$n_lights lights on the bridge:"
jq -r '(.lights // [])[] | "  \(.id)   \(.metadata.name)"' ./issue-16-lights-inventory.json
write_env RESOURCE_INVENTORY_LIGHTS "$n_lights"
note "full inventory saved to ./issue-16-lights-inventory.json"
say ""
say "Pick ONE light to mutate. It gets toggled once and then restored."
ask MUTATE_LIGHT_ID "Light id:"
light="$(grpcurl -plaintext -d "{\"light_id\":\"$MUTATE_LIGHT_ID\"}" \
  "$GW" hue.v1.LightingService/GetLight)" || { warn "GetLight failed"; exit 1; }
L_NAME="$(jq -r '.metadata.name' <<<"$light")"
live_on="$(jq -r '.on.on // false' <<<"$light")"
WAS_BRI="$(jq -r '.dimming.brightness // empty' <<<"$light")"

# The restore target is whatever the FIRST run recorded, before anything was
# touched — so a Ctrl-C between the toggle and the restore, then a re-run,
# still puts the light back where it started rather than freezing the toggle.
prev_id="$(_existing BASELINE_LIGHT_ID || true)"
prev_on="$(_existing BASELINE_ON || true)"
if [[ "$prev_id" == "$MUTATE_LIGHT_ID" && -n "$prev_on" ]]; then
  WAS_ON="$prev_on"
  say "  \"$L_NAME\"  —  now on=$live_on; a previous run recorded on=$WAS_ON before touching it"
  say "  restore target: on=$WAS_ON"
else
  if [[ -n "$prev_id" && "$prev_id" != "$MUTATE_LIGHT_ID" ]]; then
    warn "a previous run's baseline was for light $prev_id (on=$prev_on)."
    warn "if that run toggled it and stopped, restore $prev_id from the Hue app first."
    confirm "Continue with \"$L_NAME\" instead?" || exit 1
  fi
  WAS_ON="$live_on"
  say "  \"$L_NAME\"  —  on=$WAS_ON  brightness=${WAS_BRI:-n/a}"
fi
confirm "Use \"$L_NAME\" for the write test?" || exit 1
write_env MUTATE_LIGHT_ID    "$MUTATE_LIGHT_ID"
write_env MUTATE_LIGHT_NAME  "$L_NAME"
write_env BASELINE_LIGHT_ID  "$MUTATE_LIGHT_ID"
write_env BASELINE_ON        "$WAS_ON"
write_env LIGHT_STATE_BEFORE "on=$WAS_ON brightness=${WAS_BRI:-n/a}"

# ── smoke: change + restore ─────────────────────────────────────────────
stage "Smoke: change the light, then restore it"
if [[ "$WAS_ON" == "true" ]]; then
  cmd='{"on":{"on":false}}'; human="OFF"
else
  cmd='{"on":{"on":true}}';  human="ON"
fi
say "Turning \"$L_NAME\" $human ..."
grpcurl -plaintext -d "{\"light_id\":\"$MUTATE_LIGHT_ID\",\"command\":$cmd}" \
  "$GW" hue.v1.LightingService/UpdateLight | jq -c '{updated:[(.updated // [])[].rid], errors}'
confirm "Did \"$L_NAME\" visibly turn $human?" \
  && seen="yes" || seen="NOT seen"
say "Restoring on=$WAS_ON ..."
grpcurl -plaintext \
  -d "{\"light_id\":\"$MUTATE_LIGHT_ID\",\"command\":{\"on\":{\"on\":$WAS_ON}}}" \
  "$GW" hue.v1.LightingService/UpdateLight | jq -c '{updated:[(.updated // [])[].rid], errors}'
now_on="$(grpcurl -plaintext -d "{\"light_id\":\"$MUTATE_LIGHT_ID\"}" \
  "$GW" hue.v1.LightingService/GetLight | jq -r '.on.on // false')"
if [[ "$now_on" == "$WAS_ON" ]]; then
  say "restored (on=$now_on)"
  write_env WRITE_TEST "change $human $seen; restored on=$now_on"
  write_env BASELINE_LIGHT_ID ""
  write_env BASELINE_ON ""
else
  warn "light reads on=$now_on, expected $WAS_ON — set it back from the Hue app"
  write_env WRITE_TEST "change $human $seen; restore MISMATCH on=$now_on (expected $WAS_ON)"
fi

# ── smoke: event stream ─────────────────────────────────────────────────
stage "Smoke: event stream"
: > "$SUB"
grpcurl -plaintext -d "{\"resource_ids\":[\"$MUTATE_LIGHT_ID\"]}" \
  "$GW" hue.v1.EventService/Subscribe > "$SUB" 2>&1 &
SUBPID=$!
sleep 2
kill -0 "$SUBPID" 2>/dev/null || { warn "the subscription exited immediately:"; cat "$SUB"; exit 1; }
say "Subscribed, filtered to \"$L_NAME\" (pid $SUBPID)."
# The gateway only forwards events for changes made after its own upstream
# stream is up, which can lag a fresh subscriber by a moment. Give it one.
sleep 5
say "Now change that light from the Hue app on your phone — brightness or colour."
pause "Enter once you've made the change and seen it happen."
say "watching the stream for up to 40s ..."
for _ in $(seq 1 20); do
  [[ "$(count_in "$SUB" '"change"')" != 0 ]] && break
  sleep 2
done
if [[ "$(count_in "$SUB" '"change"')" != 0 ]]; then
  say "change event(s) arrived on the stream — last lines:"
  tail -n 15 "$SUB" | sed 's/^/    /'
  write_env EVENT_STREAM "change event received"
else
  warn "no change event on the stream after 40s"
  tail -n 20 "$SUB" | sed 's/^/    /' || true
  if confirm "Change the light once more and retry the watch?"; then
    for _ in $(seq 1 20); do
      [[ "$(count_in "$SUB" '"change"')" != 0 ]] && break
      sleep 2
    done
  fi
  if [[ "$(count_in "$SUB" '"change"')" != 0 ]]; then
    say "change event arrived — last lines:"
    tail -n 15 "$SUB" | sed 's/^/    /'
    write_env EVENT_STREAM "change event received (second attempt)"
  else
    confirm "Continue anyway?" || exit 1
    write_env EVENT_STREAM "NOT observed"
  fi
fi

# ── smoke: forced disconnect ────────────────────────────────────────────
stage "Smoke: force a disconnect — expect a gap, then a resync"
say "The subscription is still open. Now cut the bridge off the network:"
step "unplug its Ethernet cable (or its power) for ~15 seconds,"
step "then reconnect it."
pause "Enter the moment you've plugged it back in."
say "Waiting up to 90s for the gateway to reconnect and announce the gap ..."
for _ in $(seq 1 45); do
  [[ "$(count_in "$SUB" 'CAUSE_RECONNECTED')" != 0 ]] && break
  sleep 2
done
if [[ "$(count_in "$SUB" 'CAUSE_RECONNECTED')" != 0 ]]; then
  say "gap announced (this is the POSSIBLE_GAP the issue asks for):"
  grep -A4 'CAUSE_RECONNECTED' "$SUB" | tail -n 12 | sed 's/^/    /'
  sleep 5
  resync="$(awk '/CAUSE_RECONNECTED/{f=1} f&&/"change"/{c++} END{print c+0}' "$SUB")"
  say "synthetic change events emitted after the gap: $resync"
  say "(resync re-reads every light and emits one change per difference it finds)"
  write_env DISCONNECT_TEST "CAUSE_RECONNECTED seen; post-gap change events=$resync"
else
  warn "no gap seen — the outage may have been too brief to notice"
  tail -n 20 "$SUB" | sed 's/^/    /' || true
  write_env DISCONNECT_TEST "NOT observed"
fi
kill "$SUBPID" 2>/dev/null || true
SUBPID=""

# ── smoke: secret scan ──────────────────────────────────────────────────
if [[ $DEPLOY == 1 ]]; then
  stage "Smoke: confirm no secrets in the journal"
  sudo journalctl -u "$UNIT" --no-pager | tee "$JOURNAL" >/dev/null
  scanfile="$JOURNAL"; scanwhat="journal"
else
  stage "Smoke: confirm no secrets in the gateway log"
  scanfile="$GWLOG"; scanwhat="gateway log"
fi
app_hits="$(count_in "$scanfile" "$APP_KEY")"
cli_hits=0
[[ -n "$CLIENT_KEY" ]] && cli_hits="$(count_in "$scanfile" "$CLIENT_KEY")"
if [[ "$app_hits" == 0 && "$cli_hits" == 0 ]]; then
  say "clean — neither the Application Key nor the Client Key appears in the $scanwhat"
  write_env SECRET_SCAN "clean ($scanwhat)"
else
  warn "SECRET MATERIAL IN THE ${scanwhat^^} — app key x$app_hits, client key x$cli_hits"
  write_env SECRET_SCAN "LEAK app=$app_hits client=$cli_hits ($scanwhat)"
fi
if [[ $DEPLOY == 1 ]]; then rm -f "$JOURNAL"; fi
write_env SMOKE_FINISHED_AT "$(date -Is)"

if [[ $DEPLOY == 0 && -n "$GWPID" ]]; then
  kill "$GWPID" 2>/dev/null || true
  GWPID=""
  say "stopped the gateway."
fi

note "The registry at $REG holds the bridge secrets. Keep it for re-runs, or"
note "shred it now: shred -u \"$REG\""

finish
