#!/usr/bin/env bash
#
# Compile the .proto files into the Python the Gateway imports.
#
# Output lands in `src/hue/`, gitignored and regenerated by the Nix build and
# on dev shell entry, so generated code can never drift from the definitions
# it came from — see docs/adr/0001-custom-openapi-to-proto-generator.md.
#
# That path is not a preference. protoc derives a generated module's import
# path from the .proto file's path relative to the proto path, so
# `hue/v1/lighting.proto` produces code that imports itself as
# `hue.v1.lighting_pb2`, and whatever directory it lands in has to be a
# package root for that to resolve. Burying it inside `hue_grpc` instead means
# rewriting protoc's own import statements afterwards, which puts a sed script
# between the build and code that has to be correct.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
destination="$root/src"
# The dev shell's python is on PATH and has grpcio-tools; the Nix build hands
# over a python built for the purpose, because its own is for building with.
python="${PYTHON:-python}"

# A .proto that no longer exists must take its generated module with it.
rm -rf "$destination/hue"

"$python" -m grpc_tools.protoc \
    --proto_path="$root/proto" \
    --python_out="$destination" \
    --pyi_out="$destination" \
    --grpc_python_out="$destination" \
    "$root"/proto/hue/v1/*.proto

# protoc writes no package markers, and setuptools finds packages by them.
touch "$destination/hue/__init__.py" "$destination/hue/v1/__init__.py"
